
infinite: infinite.c
	gcc -g infinite.c -oinfinite

mycat: mycat.c
	gcc -g mycat.c -omycat 

crash: crash.c
	gcc -g crash.c -lbsd -ocrash 

debugdemo: debugdemo.c
	gcc -g debugdemo.c -odebugdemo

clean:
	rm infinite mycat crash debugdemo
